---
abstract: 'like Yanick? Be like Yanick!'
author:
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Task-BeLike-YANICK
provides:
  Task::BeLike::YANICK:
    file: lib/Task/BeLike/YANICK.pm
    version: v0.9.0
requires:
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/yanick/Task-BeLike-YANICK/issues
  homepage: https://github.com/yanick/Task-BeLike-YANICK
  repository: https://github.com/yanick/Task-BeLike-YANICK.git
version: 0.9.0
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
x_contributor_covenant:
  version: 0.01
x_contributors:
  - 'Yanick Champoux <yanick@babyl.dyndns.org>'
x_generated_by_perl: v5.20.2
x_serialization_backend: 'YAML::Tiny version 1.67'
