---
name: Task-BeLike-YANICK
version: 0.2.0
author:
  - 'Yanick Champoux <yanick@cpan.org>'
abstract: 'like Yanick? Be like Yanick!'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  App::Ack: 0
  Catalyst::Runtime: 0
  Git::CPAN::Patch: 0
  HTML::Mason: 0
  Moose: 0
  MooseX::Declare: 0
  Perl::Critic: 0
  Perl::Tidy: 0
  Template: 0
  Test::Class: 0
  WWW::Mechanize: 0
  XML::LibXML: 0
  XML::Simple: 0
  XML::Writer: 0
  XML::XPathScript: 0
  autodie: 0
build_requires:
  Module::Build: 0
provides:
  Task::BeLike::YANICK:
    file: lib/Task/BeLike/YANICK.pm
    version: 0.2.0
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
